import os

path = 'products/website/apps/researchlab/css/dashboard.css'

lines = []
lines.append('/* dashboard.css — Рабочий стол исследователя: виджеты со статистикой */')
lines.append('')
lines.append('.dashboard-widgets {')
lines.append('  margin-bottom: 40px;')
lines.append('  max-width: 100%;')
lines.append('  min-width: 0;')
lines.append('  padding-inline: var(--space-3);')
lines.append('  overflow-x: hidden;')
lines.append('}')
lines.append('')
lines.append('.dw-summary {')
lines.append('  margin-bottom: var(--space-5);')
lines.append('  padding: 14px 16px 0;')
lines.append('  background: var(--bg-card);')
lines.append('  border: 1px solid var(--border-light);')
lines.append('  border-radius: 8px;')
lines.append('  box-shadow: var(--shadow-card);')
lines.append('  max-width: 100%;')
lines.append('  min-width: 0;')
lines.append('  box-sizing: border-box;')
lines.append('}')
lines.append('.dw-summary-heading { display: flex; align-items: flex-end; justify-content: space-between; gap: 16px; padding-bottom: 10px; }')
lines.append('.dw-summary-kicker { display: block; color: var(--accent-gold); font-size: 0.6rem; letter-spacing: 0.16em; text-transform: uppercase; }')
lines.append('.dw-summary-heading h2 { margin: 2px 0 0; color: var(--text-primary); font-family: var(--font-heading); font-size: 1.1rem; font-weight: 600; }')
lines.append('.dw-summary-date { flex-shrink: 0; color: var(--text-muted); font-family: var(--font-mono); font-size: 0.7rem; }')
lines.append('.dw-summary-item {')
lines.append('  min-width: 0;')
lines.append('  padding: 10px 8px;')
lines.append('  text-align: center;')
lines.append('  text-decoration: none;')
lines.append('  color: var(--text-primary);')
lines.append('  background: var(--bg-tertiary, #f7f1e5);')
lines.append('  border-radius: 6px;')
lines.append('  box-shadow: var(--shadow-card);')
lines.append('  transition: transform var(--dur-2) var(--ease-standard), box-shadow var(--dur-2) var(--ease-standard);')
lines.append('  overflow-wrap: anywhere;')
lines.append('  word-break: break-word;')
lines.append('}')
lines.append('.dw-summary-item--link:hover, .dw-summary-item--link:focus-visible { transform: translateY(-2px); box-shadow: var(--shadow-hover); outline: none; }')
lines.append('.dw-summary-value {')
lines.append('  display: block;')
lines.append('  color: var(--text-primary);')
lines.append("  font-family: var(--font-heading), Georgia, 'Times New Roman', serif;")
lines.append('  font-size: clamp(1.4rem, 2.5vw, 2rem);')
lines.append('  font-weight: 700;')
lines.append('  line-height: 1;')
lines.append('  letter-spacing: -0.02em;')
lines.append('  font-variant-numeric: tabular-nums;')
lines.append('  overflow-wrap: anywhere;')
lines.append('  word-break: break-word;')
lines.append('}')
lines.append('/* Цифры сводки не зависят от .reveal: IO мог оставить opacity:0 до пересечения. */')
lines.append('.dw-summary-item,')
lines.append('.dw-summary-value { opacity: 1; visibility: visible; }')
lines.append('.dw-summary-label { display: block; margin-top: 6px; color: var(--text-muted); font-size: 0.65rem; letter-spacing: 0.05em; line-height: 1.25; text-transform: uppercase; }')
lines.append('.dw-counter-delta { display: block; min-height: 12px; margin-top: 4px; color: var(--text-muted); font-size: 0.65rem; line-height: 1.2; overflow-wrap: anywhere; word-break: break-word; }')
lines.append('.dw-counter-delta--up { color: #5e7d3a; }')
lines.append('')
lines.append('@media (max-width: 390px) {')
lines.append('  .dw-summary-grid { grid-template-columns: 1fr; }')
lines.append('  .dw-summary-item { padding: 10px 10px; }')
lines.append('  .dw-summary-value { font-size: 28px; }')
lines.append('}')
lines.append('@media (min-width: 391px) and (max-width: 560px) {')
lines.append('  .dw-summary-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }')
lines.append('}')
lines.append('')
lines.append('.dw-grid {')
lines.append('  display: grid;')
lines.append('  grid-template-columns: repeat(auto-fit, minmax(min(320px, 100%), 1fr));')
lines.append('  gap: var(--space-5);')
lines.append('  max-width: 100%;')
lines.append('  min-width: 0;')
lines.append('}')
lines.append('.dw-widget {')
lines.append('  background: var(--bg-card);')
lines.append('  border: 1px solid var(--border-light);')
lines.append('  border-radius: var(--radius-sm);')
lines.append('  padding: 18px 16px;')
lines.append('  box-shadow: var(--shadow-soft);')
lines.append('  max-width: 100%;')
lines.append('  min-width: 0;')
lines.append('  box-sizing: border-box;')
lines.append('  overflow-wrap: anywhere;')
lines.append('}')
lines.append('.dw-widget h3 {')
lines.append('  font-family: var(--font-heading);')
lines.append('  font-size: 19px;')
lines.append('  font-weight: 600;')
lines.append('  font-style: normal;')
lines.append('  color: var(--text-primary);')
lines.append('  margin-bottom: 12px;')
lines.append('  padding-bottom: var(--space-2);')
lines.append('  border-bottom: 1px solid var(--border-light);')
lines.append('}')
lines.append('.dw-widget-heading { display: flex; align-items: baseline; justify-content: space-between; gap: 14px; border-bottom: 1px solid var(--border-light); }')
lines.append('.dw-widget-heading h3 { margin-bottom: 0; border-bottom: 0; }')
lines.append('.dw-completeness-average { flex-shrink: 0; color: var(--accent-gold); font-family: var(--font-heading); font-size: 19px; }')
lines.append('.dw-completeness-average span { color: var(--text-muted); font-family: var(--font-body); font-size: var(--text-xs); font-weight: 400; }')
lines.append('.dw-widget-wide { grid-column: 1 / -1; }')
lines.append('')
lines.append('/* Метрики движения материалов и контура надёжности. */')
lines.append('.dw-metric-grid {')
lines.append('  display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 8px;')
lines.append('  max-width: 100%;')
lines.append('}')
lines.append('.dw-metric {')
lines.append('  display: flex; flex-direction: column; gap: 4px; min-width: 0;')
lines.append('  padding: 10px 12px; border-left: 3px solid var(--border-light); background: var(--bg-tertiary);')
lines.append('  border-radius: var(--radius-sm); box-shadow: var(--shadow-card);')
lines.append('  transition: transform var(--dur-2) var(--ease-standard), box-shadow var(--dur-2) var(--ease-standard);')
lines.append('  overflow-wrap: anywhere;')
lines.append('}')
lines.append('.dw-metric:hover { transform: translateY(-2px); box-shadow: var(--shadow-hover); }')
lines.append('.dw-metric-value { color: var(--text-primary); font-family: var(--font-heading); font-size: 22px; font-weight: 700; line-height: 1; letter-spacing: -0.02em; font-variant-numeric: tabular-nums; }')
lines.append('.dw-metric-label { color: var(--text-muted); font-size: var(--text-xs); letter-spacing: 0.04em; text-transform: uppercase; }')
lines.append('.dw-metric--new, .dw-metric--verified { border-left-color: var(--accent-gold); }')
lines.append('.dw-metric--updated, .dw-metric--published { border-left-color: var(--text-secondary); }')
lines.append('.dw-metric--review { border-left-color: #b8860b; }')
lines.append('.dw-metric--hypothesis { border-left-color: #7a6b9e; }')
lines.append('.dw-widget-note { margin: 10px 0 0; color: var(--text-muted); font-size: var(--text-xs); line-height: 1.5; }')
lines.append('')
lines.append('/* Полнота данных: список книг/разделов. */')
lines.append('.dw-completeness-list { display: flex; flex-direction: column; max-width: 100%; }')
lines.append('.dw-completeness-item { padding: 10px 0; border-bottom: 1px solid var(--border-light); color: var(--text-primary); text-decoration: none; }')
lines.append('.dw-completeness-item:hover, .dw-completeness-item:focus-visible { color: var(--text-primary); background: rgb(var(--accent-gold-rgb) / 0.10); outline: none; }')
lines.append('.dw-completeness-title { min-width: 0; font-weight: 600; }')
lines.append('.dw-completeness-meta { color: var(--text-muted); font-family: var(--font-mono); font-size: var(--text-xs); white-space: nowrap; }')
lines.append('.dw-completeness-missing { display: flex; flex-wrap: wrap; gap: 5px; margin-top: 4px; }')
lines.append('.dw-completeness-missing span { padding: 2px 6px; border-left: 2px solid #b8860b; background: var(--bg-tertiary); color: var(--text-secondary); font-size: 11px; }')
lines.append('')
lines.append('/* Гистограмма механизмов подмены */')
lines.append('.dw-bars { display: flex; flex-direction: column; gap: 8px; max-width: 100%; }')
lines.append('.dw-bar-row {')
lines.append('  display: flex; align-items: center; justify-content: space-between; gap: 10px;')
lines.append('  padding: var(--space-2) 0; border-bottom: 1px solid var(--border-light);')
lines.append('  max-width: 100%; box-sizing: border-box;')
lines.append('}')
lines.append('.dw-bar-label {')
lines.append('  width: 116px; flex-shrink: 0; font-size: 13px; color: var(--text-secondary);')
lines.append('  text-align: left; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;')
lines.append('}')
lines.append('.dw-bar-track {')
lines.append('  flex: 1 1 120px; min-width: 0; max-width: 100%;')
lines.append('  background: var(--bg-tertiary); border-radius: 3px; height: 16px; overflow: hidden;')
lines.append('}')
lines.append('.dw-bar-fill {')
lines.append('  height: 100%; background: var(--accent-gold); border-radius: 3px;')
lines.append('  transition: width 0.6s ease;')
lines.append('}')
lines.append('.dw-bar-value { width: 44px; flex-shrink: 0; font-size: 12px; color: var(--text-muted); font-family: var(--font-mono); }')
lines.append('')
lines.append('/* Последние разборы */')
lines.append('.dw-list { display: flex; flex-direction: column; gap: 8px; max-width: 100%; }')
lines.append('.dw-list-item {')
lines.append('  display: flex; align-items: center; justify-content: space-between; gap: 10px;')
lines.append('  padding: var(--space-2) 0; border-bottom: 1px solid var(--border-light);')
lines.append('  background: var(--bg-tertiary); text-decoration: none; color: var(--text-primary);')
lines.append('  transition: background var(--motion-base), color var(--motion-base);')
lines.append('  max-width: 100%; box-sizing: border-box;')
lines.append('}')
lines.append('.dw-list-item:hover { background: rgb(var(--accent-gold-rgb) / 0.10); color: var(--accent-gold); }')
lines.append('.dw-list-title { min-width: 0; flex: 1; font-weight: 600; font-size: 14px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }')
lines.append('.dw-list-meta { flex-shrink: 0; font-size: 11px; color: var(--text-muted); margin-top: 0; text-align: right; }')
lines.append('')
lines.append('/* Живая лента: хроника последних изменений материалов. */')
lines.append('.dw-ticker { overflow: hidden; border: 1px solid var(--border-light); background: var(--bg-tertiary); max-width: 100%; }')
lines.append('.dw-ticker-track { display: flex; width: max-content; animation: dw-ticker-scroll 75s linear infinite; }')
lines.append('.dw-ticker:hover .dw-ticker-track, .dw-ticker:focus-within .dw-ticker-track { animation-play-state: paused; }')
lines.append('.dw-ticker-item {')
lines.append('  display: flex; align-items: center; gap: 8px;')
lines.append('  width: min(540px, 78vw); min-height: 46px; padding: 8px 12px;')
lines.append('  border-right: 1px solid var(--border-light); color: var(--text-primary); text-decoration: none;')
lines.append('  flex: 0 0 auto; box-sizing: border-box;')
lines.append('}')
lines.append('a.dw-ticker-item:hover, a.dw-ticker-item:focus-visible { background: rgb(var(--accent-gold-rgb) / 0.12); color: var(--text-primary); outline: none; }')
lines.append('.dw-ticker-date { flex: 0 0 auto; color: var(--text-muted); font-family: var(--font-mono); font-size: var(--text-xs); }')
lines.append('.dw-ticker-type { flex: 0 0 auto; padding: 2px 5px; border-left: 2px solid var(--text-secondary); color: var(--text-secondary); font-size: 9px; line-height: 1.1; text-transform: uppercase; }')
lines.append('.dw-ticker-type--new { border-left-color: var(--accent-gold); color: var(--text-gold); }')
lines.append('.dw-ticker-type--updated { border-left-color: #b8860b; }')
lines.append('.dw-ticker-text { min-width: 0; overflow: hidden; font-size: var(--text-xs); text-overflow: ellipsis; white-space: nowrap; }')
lines.append('@keyframes dw-ticker-scroll { to { transform: translateX(-50%); } }')
lines.append('')
lines.append('/* Очередь проверки: разрывы опор в материалах needs-review. */')
lines.append('.dw-review-list { display: flex; flex-direction: column; max-width: 100%; }')
lines.append('.dw-review-item {')
lines.append('  display: grid; grid-template-columns: minmax(160px, 1fr) auto; gap: 5px 14px;')
lines.append('  padding: 10px 0; border-bottom: 1px solid var(--border-light);')
lines.append('  color: var(--text-primary); text-decoration: none;')
lines.append('  max-width: 100%; box-sizing: border-box;')
lines.append('}')
lines.append('.dw-review-item:hover, .dw-review-item:focus-visible { color: var(--text-primary); background: rgb(var(--accent-gold-rgb) / 0.10); outline: none; }')
lines.append('.dw-review-title { min-width: 0; font-weight: 600; }')
lines.append('.dw-review-meta { color: var(--text-muted); font-family: var(--font-mono); font-size: var(--text-xs); white-space: nowrap; }')
lines.append('.dw-review-missing { grid-column: 1 / -1; display: flex; flex-wrap: wrap; gap: 5px; max-width: 100%; }')
lines.append('.dw-review-missing span { padding: 2px 6px; border-left: 2px solid #b8860b; background: var(--bg-tertiary); color: var(--text-secondary); font-size: 11px; }')
lines.append('')
lines.append('/* Древо Книг: сетка 3 колонки, компактные карточки */')
lines.append('.book-grid {')
lines.append('  display: grid; grid-template-columns: repeat(3, minmax(0, 1fr));')
lines.append('  gap: 10px; max-width: 100%;')
lines.append('}')
lines.append('.book-card {')
lines.append('  display: grid; grid-template-columns: auto minmax(0, 1fr) auto;')
lines.append('  grid-template-areas:')
lines.append('    "icon name name"')
lines.append('    "track track status";')
lines.append('  gap: 4px 12px; align-items: center;')
lines.append('  min-width: 0; min-height: 0; padding: 10px 12px;')
lines.append('  border: 1px solid var(--border-light); border-radius: 8px;')
lines.append('  box-shadow: var(--shadow-soft); color: var(--text-primary); text-align: left;')
lines.append('  cursor: pointer; transition: transform var(--motion-base), box-shadow var(--motion-base), border-color var(--motion-base);')
lines.append('  box-sizing: border-box; max-width: 100%;')
lines.append('}')
lines.append('.book-card:hover, .book-card:focus-visible {')
lines.append('  transform: translateY(-2px); border-color: var(--accent-gold);')
lines.append('  box-shadow: 0 5px 14px rgb(var(--accent-gold-rgb) / 0.2); outline: none;')
lines.append('}')
lines.append('.book-card--completed { background: rgb(var(--accent-gold-rgb) / 0.18); }')
lines.append('.book-card--in-progress { background: #fff7d6; }')
lines.append('.book-card--not-started, .book-card--loading { background: var(--bg-tertiary); }')
lines.append('.book-card-icon {')
lines.append('  grid-area: icon;')
lines.append('  color: var(--text-gold); font-family: var(--font-paleo); font-size: 28px;')
lines.append('  line-height: 1;')
lines.append('}')
lines.append('.book-card-name {')
lines.append('  grid-area: name; min-width: 0; overflow: hidden; text-overflow: ellipsis;')
lines.append('  font-family: var(--font-serif); font-size: 15px; font-weight: 600; white-space: nowrap;')
lines.append('}')
lines.append('.book-card-track {')
lines.append('  grid-area: track; display: block; width: auto; height: 7px; overflow: hidden;')
lines.append('  background: var(--bg-tertiary); border-radius: 4px;')
lines.append('}')
lines.append('.book-card-fill {')
lines.append('  display: block; height: 100%; background: var(--accent-gold);')
lines.append('  border-radius: var(--radius-xs); transition: width 0.6s ease;')
lines.append('}')
lines.append('.book-card-status {')
lines.append('  grid-area: status; min-width: 0; overflow: hidden; text-overflow: ellipsis; text-align: right;')
lines.append('  color: var(--text-secondary); font-size: var(--text-xs); line-height: 1.2; white-space: nowrap;')
lines.append('}')
lines.append('.book-card--not-started .book-card-fill, .book-card--loading .book-card-fill { background: var(--border-light); }')
lines.append('')
lines.append('@media (max-width: 720px) {')
lines.append('  .dw-grid { grid-template-columns: 1fr; }')
lines.append('  .dw-summary-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }')
lines.append('  .dw-summary-item:nth-child(4) { border-left: 0; }')
lines.append('  .dw-bar-label { width: 96px; font-size: 12px; }')
lines.append('  .book-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }')
lines.append('  .book-card { padding: 10px 12px; }')
lines.append('}')
lines.append('@media (max-width: 390px) {')
lines.append('  .dashboard-widgets,')
lines.append('  .dw-summary,')
lines.append('  .dw-widget,')
lines.append('  .dw-grid {')
lines.append('    min-width: 0;')
lines.append('    max-width: 100%;')
lines.append('    padding-inline: var(--space-3);')
lines.append('    overflow-x: hidden;')
lines.append('    align-self: start;')
lines.append('    justify-self: stretch;')
lines.append('  }')
lines.append('')
lines.append('  .dw-summary { padding: var(--space-3) var(--space-3) 0; max-width: 100%; margin-inline: auto; }')
lines.append('  .dw-summary-heading { display: block; }')
lines.append('  .dw-summary-date { display: block; margin-top: var(--space-2); }')
lines.append('  .dw-summary-grid { grid-template-columns: 1fr; max-width: 100%; margin-inline: auto; }')
lines.append('  .dw-summary-item + .dw-summary-item { border-left: 0; border-top: 1px solid var(--border-light); }')
lines.append('  .dw-summary-value { font-size: 29px; }')
lines.append('  .dw-widget { padding: var(--space-3); max-width: 100%; margin-inline: auto; }')
lines.append('  .dw-widget h3 { font-size: 18px; margin-bottom: 10px; padding-bottom: var(--space-2); }')
lines.append('  .dw-widget-heading { align-items: center; flex-direction: column; gap: var(--space-2); text-align: center; }')
lines.append('  .dw-completeness-average { font-size: 18px; }')
lines.append('  .dw-bar-row,')
lines.append('  .dw-list-item { align-items: center; flex-wrap: wrap; justify-content: center; text-align: center; }')
lines.append('  .dw-bar-label,')
lines.append('  .dw-list-title { width: 100%; text-align: center; white-space: normal; overflow-wrap: anywhere; }')
lines.append('  .dw-bar-track { flex: 1 1 120px; min-width: 0; max-width: 100%; }')
lines.append('  .dw-list-meta { width: 100%; text-align: center; }')
lines.append('  .book-grid { grid-template-columns: 1fr; max-width: 100%; margin-inline: auto; }')
lines.append('  .dw-metric-grid { grid-template-columns: 1fr; max-width: 100%; margin-inline: auto; }')
lines.append('  .dw-review-item { grid-template-columns: 1fr; gap: var(--space-2); max-width: 100%; margin-inline: auto; }')
lines.append('  .dw-review-meta { overflow-wrap: anywhere; text-align: center; white-space: normal; }')
lines.append('')
lines.append('  .dw-bars,')
lines.append('  .dw-ticker {')
lines.append('    width: 100%;')
lines.append('    max-width: 100%;')
lines.append('  }')
lines.append('  .dw-ticker-track { width: max-content; }')
lines.append('  .dw-ticker-item {')
lines.append('    flex: 0 0 100%;')
lines.append('    width: 100%;')
lines.append('    min-width: 0;')
lines.append('    max-width: 100%;')
lines.append('    box-sizing: border-box;')
lines.append('    padding: var(--space-2) var(--space-3);')
lines.append('    word-break: break-word;')
lines.append('  }')
lines.append('  .dw-bar-row,')
lines.append('  .dw-list-item {')
lines.append('    align-items: center;')
lines.append('    flex-wrap: wrap;')
lines.append('    justify-content: center;')
lines.append('    text-align: center;')
lines.append('    max-width: 100%;')
lines.append('    box-sizing: border-box;')
lines.append('  }')
lines.append('  .dw-bar-track {')
lines.append('    flex: 1 1 120px;')
lines.append('    min-width: 0;')
lines.append('    max-width: 100%;')
lines.append('  }')
lines.append('  .dw-summary-item,')
lines.append('  .dw-summary-value,')
lines.append('  .dw-counter-delta {')
lines.append('    overflow-wrap: anywhere;')
lines.append('    word-break: break-word;')
lines.append('  }')
lines.append('}')
lines.append('')
lines.append('@media (prefers-reduced-motion: reduce) {')
lines.append('  .dw-ticker { overflow-x: auto; }')
lines.append('  .dw-ticker-track { animation: none; }')
lines.append('}')
lines.append('')
lines.append('print("OK dashboard.css written")')

with open(path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')